### ISSUE TITLE
Release into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros-visualization/rqt_top#3]
It looks like all of the dependencies for this package are available in Melodic, so it would be great to get it released there.  Thanks in advance.

**Comment by clalancette** [comment]
Ping?  Can we get this released into Melodic, please?  Thanks.

**Comment by dlaz** [comment]
I will take a look at this.

**Comment by clalancette** [comment]
Thank you!

**Comment by dlaz** [comment]
I confirmed that it works in melodic/bionic, but I don't have write access to ros-gbp/rqt_top-release.git, so I can't create the release.

**Comment by dirk-thomas** [comment]
I invited you as a collaborator on that repo.

**Comment by dlaz** [comment]
https://github.com/ros/rosdistro/pull/17659

**Comment by clalancette** [comment]
This was done a long time ago, so closing.
